### PR TITLE
adding the howto paragraph

### PR DESCRIPTION
**Pull request by ecestor03**
Adding a new for for Paragrpah Howto (trello115)

### CODE REVIEW

**Comment by ecestor03** [comment]
please check

**Comment by jcheek** [comment]
The config looks good but the directory is wrong.  It should be `config_zds/sync`.  Please fix and resubmit.

**Review by jcheek — CHANGES_REQUESTED** [review]
what about `paragraph.settings.yml`?

**Comment by ecestor03** [comment]
> what about `paragraph.settings.yml`?

Done Joseph

**Review by jcheek — APPROVED** [review]

**Pull request merged**
